spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8081
  servlet:
    context-path: /cloud-eureka

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/cloud-eureka/eureka/